### ISSUE TITLE
по поводу бота обратной связи.

### ISSUE THREAD

**Issue by kabalik** [MasterGroosha/telegram-feedback-bot#12]
добрый день! Мне интересен ваш бот обратной связи, можно ли в нем сделать так, чтобы юзер мог отправить в бот любой тип файла(видео, аудио, текст или документ либо архив), бот перенаправил этот документ админу и админ так же мог бы ответить при желании на это сообщение?

**Comment by MasterGroosha** [comment]
Приветствую. Ну вообще это так сейчас и происходит: юзер может отправить не только текст, а почти что угодно (за редким исключением). Попробуйте развернуть у себя и проверьте сами. Или что-то не работает?

**Comment by kabalik** [comment]
когда отправляю картинку или видео, либо документ бот его не перенаправляет админу. И вроде как ничего не просходит

**Comment by MasterGroosha** [comment]
![IMG_3172](https://github.com/MasterGroosha/telegram-feedback-bot/assets/2780044/31c2de2f-a4a0-4d54-97eb-45f9025ac138)

Только что проверил, без проблем реагирует на файлы. Из какого коммита взят код? Какой докер-образ, если используется? Что в логах?
