### ISSUE TITLE
add README on English

### ISSUE THREAD

**Issue by lgg** [MasterGroosha/telegram-feedback-bot#2]
I can create PR, will u accept it?

**Comment by lgg** [comment]
я бы ещё добавил информацию:

* где брать chat id и что для групп его важно указывать с `-` 
* docker-compose сразу с environment прописанными

ну и следом PR на i18n надо бы сделать)

**Comment by MasterGroosha** [comment]
>  docker-compose сразу с environment прописанными

Не самая лучшая идея, на мой взгляд. То, как сделано сейчас, вполне нормально.

> где брать chat id и что для групп его важно указывать с `-`

Добавлю в ридми, если этого там ещё нет

**Comment by lgg** [comment]
@MasterGroosha 
Во-первых, спасибо огромное за бота! Если бы не он перед новогодними - совсем с ума сошёл бы. Автор - крепкого тебе здоровья и долгих лет жизни!

>Не самая лучшая идея, на мой взгляд. То, как сделано сейчас, вполне нормально.

не возражаю, оке

>Добавлю в ридми, если этого там ещё нет
Я делал по: https://stackoverflow.com/questions/32423837/telegram-bot-how-to-get-a-group-chat-id

До этого супер плотно не работал и не сразу понял, что для группы id начинается с `-`, потом вспомнил как было в ВК и стало очевидно, но если не против - то лучше такое в README добавить:

```
Переменная ADMIN_CHAT_ID должна быть числом, равным идентификатору либо лички с админом, либо группы (желательно, супергруппы), все участники которой будут считаться равноправными администраторами бота. ID групп в телеграм начинаются с `-`
```

**Comment by MasterGroosha** [comment]
> то лучше такое в README добавить

Справедливо. Только, наверное, не в README, а в `env_dist`, как раз там, где указывается переменная `ADMIN_CHAT_ID`.

> И на счёт англ ридми - ок, если его добавлю, примете Pull Request?

Так вышло, что основная разработка у меня ведётся на личном GitLab, а сюда просто зеркалируется код. Можешь создать Pull Request, но изменения оттуда я буду сливать вручную и пушить "от себя" (надо подумать, как сохранить список контрибуторов).

У меня при этом возникает другой вопрос, более глобальный: а зачем README на английском? Пардон за вопрос, но я реально хочу понять причину сего действия. Ибо если планируется показывать код иностранцам, то есть смысл мне полностью обновить комментарии в самом коде, переведя их на английский, как в других моих проектах.

**Comment by lgg** [comment]
>Только, наверное, не в README, а в env_dist, как раз там, где указывается переменная ADMIN_CHAT_ID

+++

>  но изменения оттуда я буду сливать вручную и пушить "от себя" (надо подумать, как сохранить список контрибуторов).

Можно не сохранять

> Ибо если планируется показывать код иностранцам, то есть смысл мне полностью обновить комментарии в самом коде, переведя их на английский, как в других моих проектах.

На самом деле мотивация - "душа болит". Я наткнулся на этот проект и он пушка, но тут описание только на русском, что сразу же значительно срезает потенциальную целевую аудиторию. У меня есть скромный неработающий бот почти 3х летней давности (https://github.com/lgg/vk-to-telegram-bot) - так мне до сих пор некоторые иностранцы даже в телеграм в личку стучатся и что-то спрашивают про него и в выдаче он где-то мелькает. То есть лично для меня - мотивацию можно сформулировать "сделать мир лучше" - я наткнулся на этот проект, сам им воспользовался и уверен, что в мире полно людей, кому он нужен и может быть полезным, но из-за языкового барьера многие даже банально не найдут этого бота или пройдут мимо.

Я уже после праздников закину перевод, а там посмотрим. В идеале, если вообще сможем/сможешь сделать обновление, где все текстовые переменные (ответы бота + вроде где-то ещё видео) вынесены в отдельный файл, чтобы можно было делать мультиязычность за счёт редактирования этого файла + в целом это сделает бот более универсальным, так как мне для использования как раз понадобилось только закомментить удаление ответа бота и поменять текста, больше ничего не трогал и всё запустилось "из коробки".

**Comment by lgg** [comment]
Ни в коем случае не гонюсь за звездочками, наоборот, для меня они показатель - что проект действительно кому-то полезен и нужен. 

например, репка - узкоспециализированный сборник ссылок, но за счёт английского языка уже почти 150+ звездочек = 150+ человек, которые им воспользовались по назначению и кому это помогло/съэкономило время.

Ставлю, что если в данном боте добавить README на английском + причесать оформление репки на англ (описание и тд) - то народу сюда повалит уйма и через год будет уже под 1000 активных юзеров.

**Comment by MasterGroosha** [comment]
@lgg Спасибо за подробное описание!
Я думаю, на первой итерации можно сделать переводы в одном JSON-файле, как в [другом моём боте](https://github.com/MasterGroosha/telegram-report-bot).
Полноценный i18n на gettext делать не хочу принципиально, но думаю над тем, как бы прикрутить [Fluent от Mozilla](https://projectfluent.org/) (есть демка, осталось в реальный проект перенести).

> то народу сюда повалит уйма и через год будет уже под 1000 активных юзеров

Ха! Это заблуждение, проверено :)

**Comment by MasterGroosha** [comment]
Добавил предупреждение об отрицательных ID у групп и каналов (и о способе их получения) в f34fd17
