### ISSUE TITLE
добавить возможность выбора - удалять или оставлять сообщения-ответы бота на действия пользователя в переписке между ботом и пользователем

### ISSUE THREAD

**Issue by lgg** [MasterGroosha/telegram-feedback-bot#3]
https://github.com/MasterGroosha/telegram-feedback-bot/blob/94626fbbcaaa7d81b663bdea1229695c0d146a25/bot/handlers/usermode.py#L16

**Comment by MasterGroosha** [comment]
Привет, зачем? Что конкретно вынести?

**Comment by lgg** [comment]
Стали использовать этого бота у себя на работе - нам нужно поведение, когда ответ бота на действие пользователя остаётся в переписке с ботом для истории. В вашем случае (можем на "ты"?) наоборот лучше, чтобы после ответа бота на действие пользователя сообщение удалялось. 
Чтобы было удобно всем - предлагаю добавить банальный флаг, показывающий необходимость удалять сообщения "ответы" бота на действия пользователя или нет.

В нашем кейсе мы сделали форк бота и закомментили эту строчку. Теперь в истории чата сообщения остаются:

![image](https://user-images.githubusercontent.com/12018713/147777642-5a4b2702-8a79-4f55-82d5-de96ab0167a1.png)

**Comment by MasterGroosha** [comment]
Хм, я изначально не предполагал даже, что такой кейс может быть. Звучит логично, добавлю флаг в конфиг. Спасибо за идею!

**Comment by MasterGroosha** [comment]
Сделано в 8be4a8a

**Comment by MasterGroosha** [comment]
upd: залил с тегом `v1.7` в DockerHub:
`docker pull groosha/telegram-feedback-bot:v1.7`
